sudo:          false
language:      node_js
node_js:
  - "17"
script:
  - npm --version
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  repo:  Radizzt/radizzt.github.io
  target_branch: gh-pages
  on:
    branch: main
